version: '3'

services:
  db1:
    restart: always

  db2:
    restart: always

  backend:
    restart: always
    volumes:
      - backend:/project

  frontend:
    command: npm run build
    volumes:
      - frontend:/project

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile-prod
    volumes:
      - backend:/backend:ro
      - frontend:/frontend:ro
      - /home/jenkins/ssl:/ssl:ro

volumes:
  frontend:
  backend:
