version: '3.7'

services:
  db:
    restart: always

  backend:
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/ssl:/ssl:ro
