services:
  nginx:
    build: nginx
    depends_on:
      - api
      - frontend
    ports:
      - "127.0.0.1:${PORT_NGINX:-80}:80"
    volumes:
      - ./nginx/svgs:/svgs

  frontend:
    container_name: frontend
    build: frontend
    command: yarn serve
    environment:
      - VITE_VUE_APP_MATOMOID=${VITE_VUE_APP_MATOMOID}
      - VITE_VUE_APP_HOTJAR=${VITE_VUE_APP_HOTJAR}
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/public:/project/public
      - ./frontend/.eslintrc.js:/project/.eslintrc.js
      - ./frontend/.prettierrc.json:/project/.prettierrc.json
      - ./frontend/vite.config.mjs:/project/vite.config.mjs
      - ./frontend/package.json:/project/package.json
      - ./frontend/index.html:/project/index.html
      - ./frontend/stats.html:/project/stats.html
      - ./frontend/yarn.lock:/project/yarn.lock
    networks:
      - nginx-network

  neo4j:
    environment:
      - NEO4J_dbms_transaction_timeout=40s
      - NEO4J_dbms_lock_acquisition_timeout=40s
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/opt/neo4j-import
    ports:
      - "127.0.0.1:${PORT_NEO4J_1:-7474}:7474"
      - "127.0.0.1:${PORT_NEO4J_2:-7687}:7687"

  api:
    volumes:
      - ./api/src:/project/src
      - ./api/svg:/project/svg
      - ./api/repository:/project/repository
      - ./api/public:/project/public
      - ./api/dataOverlay:/project/dataOverlay
      - ./api/.eslintrc.js:/project/.eslintrc.js
      - ./api/.prettierrc.json:/project/.prettierrc.json
      - ./api/test:/project/test
    command: yarn develop

  ftp:
    environment:
      - FTP_IP=127.0.0.1
      - FLAGS=-Y 0 -d -d
  pg:
    build:
      context: pg
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - ./pg/scripts:/scripts
      - ./pg/postgres-data:/var/lib/postgresql/data
      - ./pg/input_data:/input_data
    ports:
      - "127.0.0.1:5432:5432"
