version: '3'

services:
  db:
    restart: always
    image: postgres
    env_file: postgres.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - net-tier

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    depends_on:
      - backend
    links:
      - backend:backend
    volumes:
      - ./nginx/static:/static
      - ./nginx/static:/usr/share/nginx/html:ro
      - ./backend/media:/media
    ports:
      - "80:80"
    networks:
      - net-tier

  backend:
    restart: always
    depends_on:
      - db
    env_file: postgres.env
    build: ./backend
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/project
      - ./backend/static:/static
      - ./backend/media:/media
    ports:
      - "8000:8000"
    networks:
      - net-tier

networks:
  net-tier:
    driver: bridge
