services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/prod.Dockerfile
      args:
        - VITE_VUE_APP_MATOMOID=${VITE_VUE_APP_MATOMOID}
        - VITE_VUE_APP_HOTJAR=${VITE_VUE_APP_HOTJAR}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G

  api:
    command: yarn start
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G

  neo4j:
    environment:
      - NEO4J_dbms_transaction_timeout=40s
      - NEO4J_dbms_lock_acquisition_timeout=40s
      - NEO4J_dbms_memory_heap_initial__size=5G
      - NEO4J_dbms_memory_off__heap_max__size=8G
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 13G
    ulimits:
      nofile:
        soft: 80000
        hard: 90000

  ftp:
    environment:
      - FTP_IP=${FTP_IP}
      - FLAGS=-Y 1
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 200M

  pg:
    build:
      context: pg
    restart: always
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - /var/lib/docker-volumes/pg/postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          memory: 3G
        limits:
          memory: 5G

volumes:
  letsencrypt:
