version: '3'

services:
  db:
    restart: always

  db2:
    restart: always


  backend:
    restart: always
    volumes:
      - ./backend/static:/project/static
      # - ./backend/media:/media


  frontend:
    command: npm run build
    volumes:
      - ./frontend/dist:/project/dist
      - ./frontend/dist-html:/project/dist-html

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    links:
      - backend:backend
    volumes:
      - ./frontend/dist-html:/usr/share/nginx/html:ro
      - ./frontend/dist:/static
      # - ./backend/static/admin:/static/admin
      - ./backend/media:/media
