#!/bin/bash

run_lint () {

  if [[ ! -z "$2" ]]
  then
    echo "$2"
    # Prettify all selected files
    echo "$2" | xargs docker compose -f docker-compose.yml -f docker-compose-local.yml exec $1 ./node_modules/.bin/prettier --ignore-unknown --write

    # Exit if there are lint problems
    if ! docker compose -f docker-compose.yml -f docker-compose-local.yml exec $1 yarn run eslint $2 --ext .js,.vue; then
      exit 1
    fi

    # Add back the modified/prettified files to staging
    echo "$3" | xargs git add

  fi

}

# List all backend files
A_FILES=$(git diff --cached --name-only --diff-filter=ACMR -- api/src/ | sed 's| |\\ |g')
API_FILES=${A_FILES//api\/}
F_FILES=$(git diff --cached --name-only --diff-filter=ACMR -- frontend/src/ | sed 's| |\\ |g')
FRONTEND_FILES=${F_FILES//frontend\/}

run_lint api $API_FILES $A_FILES
run_lint frontend $FRONTEND_FILES $F_FILES

exit 0
