name: "Prettier"

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "/frontend: Prettify code"
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write frontend/src --config frontend/.prettierrc.json --ignore-path frontend/.prettierignore"
          # working_directory: frontend/
          only_changed: False
          dry: False
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "/api: Prettify code"
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write api/src api/test --config api/.prettierrc.json --ignore-path api/.prettierignore"
          # working_directory: api/
          only_changed: False
          dry: False
          github_token: ${{ secrets.GITHUB_TOKEN }}
